#!/usr/bin/env bash

set -euo pipefail

old="$old_version"
new="$new_version"

latest_tagged() {
  tag="$1"
  brew -q list-tagged --latest "$tag" |
    awk '{print $1}' |
    sort
}

for rhel in 7 8; do
  echo "=== rhel-$rhel"
  echo "only in $old"
  echo "        only in $new"
  comm -3 <(latest_tagged "rhaos-$old-rhel-$rhel-override") <(latest_tagged "rhaos-$new-rhel-$rhel-override")
done
