#!/usr/bin/env groovy

node() {
    checkout scm
    commonlib = load("pipeline-scripts/commonlib.groovy")

    commonlib.describeJob("olm_bundle", """
This job is meant to be triggered by remote API calls (namely from ocp4_scan). It will forward the call to 
<a href="https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Folm_bundle/">olm_bundle</a>,
that being part of a multibranch pipeline could not be configured to receive remote triggers directly.<br>
    """)

    // Expose properties for a parameterized build
    properties(
        [
            disableResume(),
            buildDiscarder(
                logRotator(
                    artifactDaysToKeepStr: '30',
                    daysToKeepStr: '30')),
            [
                $class: 'ParametersDefinitionProperty',
                parameterDefinitions: [
                    commonlib.mockParam(),
                    choice(
                        name: 'BUILD_VERSION',
                        choices: commonlib.ocpVersions,
                        description: 'OCP Version',
                    ),
                    string(
                        name: 'ASSEMBLY',
                        description: 'Assembly name.',
                        defaultValue: "stream",
                        trim: true,
                    ),
                    string(
                        name: 'DOOZER_DATA_PATH',
                        description: 'ocp-build-data fork to use (e.g. test customizations on your own fork)',
                        defaultValue: "https://github.com/openshift-eng/ocp-build-data",
                        trim: true,
                    ),
                    string(
                        name: 'DOOZER_DATA_GITREF',
                        description: '(Optional) Doozer data path git [branch / tag / sha] to use',
                        defaultValue: "",
                        trim: true,
                    ),
                    string(
                        name: 'OPERATOR_NVRS',
                        description: '(Optional) List **only** the operator NVRs you want to build bundles for, everything else gets ignored. The operators should not be mode:disabled/wip in ocp-build-data',
                        defaultValue: "",
                        trim: true,
                    ),
                    string(name: "TRIGGERED_FROM", trim: true),
                ]
            ],
        ]
    )

    commonlib.checkMock()
    currentBuild.displayName = "#${currentBuild.number} - ${params.BUILD_VERSION}"

    echo "Triggered from ${TRIGGERED_FROM}"

    build(
        job: '../aos-cd-builds/build%252Folm_bundle/',
        propagate: false,
        parameters: [
            string(name: 'BUILD_VERSION', value: params.BUILD_VERSION),
            string(name: 'ASSEMBLY', value: params.ASSEMBLY),
            string(name: 'DOOZER_DATA_PATH', value: params.DOOZER_DATA_PATH),
            string(name: 'DOOZER_DATA_GITREF', value: params.DOOZER_DATA_GITREF),
            string(name: 'OPERATOR_NVRS', value: params.OPERATOR_NVRS),
            booleanParam(name: 'DRY_RUN', value: params.DRY_RUN)
        ]
    )
}
