#!/bin/bash
# ocp-cat

usage() {
  cat <<-EOUSAGE
	ocp-cat: Display file from ocp-build-data in terminal
	Set OCP_BUILD_DATA environment variable
	usage:
	  ocp-cat file [filter]...
	examples:
	  ocp-cat stream.yml
	  ocp-cat group.yml freeze_automation
    ocp-cat group.yml arches arches_override
	  ocp-cat images/openshift-enterprise-console.yml from
	  ocp-cat images/openshift-enterprise-console.yml from.builder
	EOUSAGE
}

ocp_versions() {
  local executable commonlib
  executable="$(readlink -f "$0")"
  commonlib="${executable%/*/*/*}/pipeline-scripts/commonlib.groovy"

  [[ -f "$commonlib" ]] || {
    echo "Script assumes ocp-cat is symlinked to aos-cd-jobs to determine versions. Fail">/dev/stderr
    exit 1
  }

  awk -F'"' '
    /ocp4Versions/ { f=1 }
    f && /^]/ { exit }
    f && NF>2 { print $2 }
  ' "$commonlib" | sort --version-sort
}

show_file() {
  local branch file
  branch="origin/openshift-$1"
  file="$2"
  GIT_DIR="$OCP_BUILD_DATA/.git" \
    git show "${branch}:$file"
}

print_file() {
  local file release
  release="$1"
  file="$2"
  echo "======== $release ========"
  if command -v bat &>/dev/null; then
    show_file "$release" "$file" | bat --language "${file##*.}"
  else
    show_file
  fi
}

filter() {
  local release object
  declare -a objects
  release="$1"
  shift
  objects=$@
  local sep=""
  local jq_prog="{\"$release\": {"
  for object in ${objects[@]}; do
    [[ "$object" == keys ]] && dot="" || dot="."
    jq_prog="$(printf '%s%s"%s": %s%s' "$jq_prog" "$sep" "$object" "$dot" "$object")"
    sep=", "
  done
  jq_prog="$jq_prog }}"

  yq --yaml-output "$jq_prog"
}

main() {
  local release file
  declare -a objects
  file="$1"
  shift
  objects="$@"
  [[ "$file" == help || "$file" == "-h" || "$file" == "--help" ]] && {
    usage
    exit 0
  }
  [[ -z "$OCP_BUILD_DATA" ]] && {
    echo "Export OCP_BUILD_DATA to point to your local clone of ocp-build-data">/dev/stderr
    exit 1
  }
  [[ -z "$file" ]] && {
    usage >/dev/stderr
    exit 1
  }

  for release in $(ocp_versions); do
    if [[ -z "$objects" ]]; then
      print_file "$release" "$file"
    else
      show_file "$release" "$file" | filter "$release" "${objects[@]}"
    fi
  done
}

main "$@"
