---
children:
  - "test_pull_request_origin_check"
  - "test_pull_request_origin_integration"
  # - "test_pull_request_origin_extended_conformance_install"
  - "test_pull_request_origin_extended_conformance_install_update"
  - "test_pull_request_origin_extended_conformance_gce"
