apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openshift-bot-ssh-private-key
spec:
  data:
  - remoteRef:
      key: art/prod/openshift-bot-ssh-private-key
    secretKey: ssh_privatekey
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: synced-openshift-bot-ssh-private-key
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/ssh-auth
      metadata:
        annotations:
          tekton.dev/git-0: github.com
          tekton.dev/git-1: pkgs.devel.redhat.com
      data:
        known_hosts: |
          pkgs.devel.redhat.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDT8I6l839M7tb6V/Le8x3pGo3sTo6SG/kMrVwPQ6kUtxuaWKBLCmI1HVawfRbBz4fO+8AifdKjtOKUHcI6iPr8=
          github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        ssh-privatekey: "{{ .ssh_privatekey }}"
