#!/usr/bin/env groovy

node() {
    checkout scm
    commonlib = load("pipeline-scripts/commonlib.groovy")

    commonlib.describeJob("build-sync", """
This job is meant to be triggered by remote API calls (namely from ocp4_scan). It will forward the call to 
<a href="https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-sync">build-sync</a>,
that being part of a multibranch pipeline could not be configured to receive remote triggers directly.<br>
In this context, the only <strong>BUILD_VERSION</strong> param is required.
    """)

    // Expose properties for a parameterized build
    properties(
        [
            disableResume(),
            buildDiscarder(
                logRotator(
                    artifactDaysToKeepStr: '365',
                    daysToKeepStr: '365')),
            [
                $class: 'ParametersDefinitionProperty',
                parameterDefinitions: [
                    commonlib.mockParam(),
                    commonlib.ocpVersionParam('BUILD_VERSION', '4'),
                    string(name: "TRIGGERED_FROM", trim: true),
                ]
            ],
        ]
    )

    commonlib.checkMock()
    currentBuild.displayName = "#${currentBuild.number} - ${params.BUILD_VERSION}"

    echo "Triggered from ${TRIGGERED_FROM}"

    build(
        job: '../aos-cd-builds/build%252Fbuild-sync/',
        propagate: false,
        parameters: [
            string(name: 'BUILD_VERSION', value: params.BUILD_VERSION)
        ]
    )
}
