---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: link-pull-request-to-jira
spec:
  params:
    - name: GIT_REVISION
      value: $(body.pull_request.head.sha)
    - name: REPO_FULL_NAME
      value: $(body.repository.full_name)
    - name: PR_NUMBER
      value: $(body.number)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: link-pull-request-to-jira
spec:
  params:
    - name: REPO_FULL_NAME
    - name: PR_NUMBER
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: link-pull-request-to-jira-run-
    spec:
      pipelineRef:
        name: link-pull-request-to-jira
      params:
      - name: REPO_FULL_NAME
        value: $(params.REPO_FULL_NAME)
      - name: PR_NUMBER
        value: $(params.PR_NUMBER)
