---
parent: 'common/test_cases/origin_release_install_azure.yml'
overrides:
  sync:
    - "openshift,openshift-ansible=master"
    - "openshift,image-registry=master"
    - "openshift,kubernetes-metrics-server=master"
    - "openshift,origin-web-console-server=master"
    - "openshift,aos-cd-jobs=master"
    - "openshift,release=master"
extensions:
  parameters:
    - name: "SUITE"
      description: "Which shell file in the <a href='https://github.com/openshift/origin/tree/master/test/extended'><code>origin/test/extended/</code></a> di
rectory to run."
      default_value: "conformance"
  actions:
    - type: "script"
      title: "publish Azure image"
      repository: "release"
      timeout: 900
      script: |-
        exit 0
