---
parent: 'common/test_cases/origin_minimal.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "run code verification"
      repository: "cluster-operator"
      script: |-
        make verify
    - type: "script"
      title: "run tests"
      repository: "cluster-operator"
      script: |-
        make test
