---
parent: 'common/test_cases/origin_release_install_gce_39.yml'
overrides:
  sync:
    - "openshift,origin=release-3.9" # this is a periodic job and so must set branches
    - "openshift,openshift-ansible=release-3.9"
    - "openshift,image-registry=release-3.9"
    - "openshift,kubernetes-metrics-server=release-3.9"
    - "openshift,origin-web-console-server=release-3.9"
    - "openshift,aos-cd-jobs=master"
    - "openshift,release=master"
  email:
    - ccoleman@redhat.com
extensions:
  parameters:
    - name: SUITE
      description: "Which shell file in the <a href='https://github.com/openshift/origin/tree/master/test/extended'><code>origin/test/extended/</code></a> di
rectory to run."
      default_value: "conformance-k8s"
    - name: FORCE_BUILD
      default_value: "1"
  actions:
    - type: "host_script"
      title: "tag the latest conformance results"
      script: |-
        location="origin-ci-test/logs/${JOB_NAME}/${BUILD_NUMBER}/artifacts/scripts/conformance-k8s/artifacts"
        location_url="https://storage.googleapis.com/${location}"

        ref="${ORIGIN_TARGET_BRANCH-}"
        if [[ -z "${ref}" && -n "${JOB_SPEC-}" ]]; then
          ref="$( echo "${JOB_SPEC}" | jq  -r '.refs.base_ref' )"
        fi
        echo "${location_url}" > .latest-conformance
        gsutil cp .latest-conformance "gs://origin-ci-test/releases/openshift/origin/${ref}/.latest-conformance"
