---
parent: 'common/test_cases/ovn-kubernetes.yml'
overrides:
  provision:
    os: "rhel"
    stage: "ovn"
    provider: "aws"
extensions:
  actions:
  - type: "forward_parameters"
    parameters:
      - PULL_NUMBER
      - PULL_BASE_SHA
      - PULL_PULL_SHA
  - type: "script"
    title: "clone ovn-kubernetes and check out the correct refs"
    script: |-
      cd /go/src/github.com/openvswitch/ovn-kubernetes
      git fetch origin
      git checkout master
      git branch -D target || true
      git branch -D pr || true
      git branch target "${PULL_BASE_SHA}"
      git checkout target
      git fetch origin "pull/${PULL_NUMBER}/head:pr"
      git merge "${PULL_PULL_SHA}"
  - type: "script"
    title: "run the cri-o integration tests"
    script: |-
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags integration \
                       --become-user root \
                       --connection local \
                       /go/src/github.com/openvswitch/ovn-kubernetes/test/integration/main.yml
