---
parent: 'common/test_cases/origin_release_install_gce.yml'
overrides:
  junit_analysis: True
  sync:
    - "openshift,origin=release-3.9"
    - "openshift,aos-cd-jobs=master"
    - "openshift,image-registry=release-3.9"
    - "openshift,kubernetes-metrics-server=release-3.9"
    - "openshift,origin-web-console-server=release-3.9"
extensions:
  actions:
    - type: "script"
      title: "hold for user action"
      repository: "origin"
      timeout: 7230
      script: |-
        date
        echo "Waiting for two hours before tearing down cluster"
        sleep 7200
