---
parent: 'test_cases/test_branch_origin_extended_conformance_crio_rpm.yml'
overrides:
  junit_analysis: True
  sync_repos:
    - name: "aos-cd-jobs"
    - name: "openshift-ansible"
      type: "pull_request"
    - name: "origin"
    - name: "image-registry"
    - name: "kubernetes-metrics-server"
