---
parent: 'common/test_cases/origin_minimal.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "online-console-extensions generated template check"
      repository: "online-console-extensions"
      script: |-
        ./hack/check-generated-templates.sh
