---
parent: 'test_cases/test_branch_origin_extended_conformance_crio.yml'
overrides:
  junit_analysis: True
  sync:
    - openshift,aos-cd-jobs=master
    - openshift,image-registry=master
    - openshift,kubernetes-metrics-server=master
    - openshift,origin=master
