---
parent: 'common/test_cases/origin_built_installed_release.yml'
overrides:
  junit_analysis: False
  sync_repos:
    - name: "origin"
      type: "pull_request"
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        for pth in ${OS_ROOT:-} "$(pwd)" "$(dirname ${BASH_SOURCE})" "/data/src/github.com/openshift/origin"; do
          if [[ -e "${pth}/hack/lib/init.sh" && -e "${pth}/test/extended/setup.sh" ]]; then
            export OS_ROOT="${pth}"
            break
          fi
        done

        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/extended.test hack/env make build-extended-test

        export OPENSHIFT_SKIP_BUILD=true
        export KUBECONFIG=/etc/origin/master/admin.kubeconfig
        export TEST_ONLY=true
        export JUNIT_REPORT=true

        source "${OS_ROOT}/hack/lib/init.sh"
        source "${OS_ROOT}/test/extended/setup.sh"

        export TEST_REPORT_FILE_NAME=registry_suite
        export FOCUS="\[Feature:Image|\[registry\]"

        os::log::info "Running registry extended tests serially"
        os::test::extended::run -- -test.timeout 6h ${TEST_EXTENDED_ARGS:-}
