---
parent: 'common/test_cases/origin_built_release.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "determine the release commit for origin images"
      repository: "origin"
      script: |-
        jobs_repo="/data/src/github.com/openshift/aos-cd-jobs/"
        export ORIGIN_COMMIT=$(git log -1 --pretty=%h)
        echo $ORIGIN_COMMIT > "${jobs_repo}/ORIGIN_COMMIT"
        source hack/lib/init.sh
        export ORIGIN_BUILT_VERSION=$(os::build::rpm::format_nvra)
        echo $ORIGIN_BUILT_VERSION > "${jobs_repo}/ORIGIN_BUILT_VERSION"
    - type: "script"
      title: "build Origin"
      repository: "origin"
      timeout: 1800
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/oc hack/env make build
    - type: "script"
      title: "build service-catalog user-broker image"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        REGISTRY=openshift/ NO_DOCKER=1 make user-broker-image
    - type: "script"
      title: "build Service Catalog binary"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        unset GOPATH; hack/build-go.sh
    - type: "script"
      title: "run Service Catalog unit tests"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        NO_DOCKER=1 make test-unit
    - type: "script"
      title: "build Service Catalog image"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        make build-images
    - type: "script"
      title: "build origin images"
      repository: "origin"
      timeout: 1800
      script: |-
        hack/build-local-images.py
    - type: "script"
      title: "build Service Catalog E2E test binary"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        NO_DOCKER=1 make bin/e2e.test
    - type: "script"
      title: "start cluster with Service Catalog"
      repository: "origin"
      timeout: 1800
      script: |-
        # TODO: will cluster up change?
        ./_output/local/bin/linux/amd64/oc cluster up --loglevel=5 --tag=latest --service-catalog
        ./_output/local/bin/linux/amd64/oc login -u system:admin
        ./_output/local/bin/linux/amd64/oc describe po --all-namespaces
        kubeconfig=$(mktemp)
        ./_output/local/bin/linux/amd64/oc config view --raw > $kubeconfig
        chmod a+rw $kubeconfig
        export KUBECONFIG=$kubeconfig
    - type: "script"
      title: "Run Service Catalog E2E"
      repository: "service-catalog"
      timeout: 1800
      script: |-
        SERVICECATALOGCONFIG=$KUBECONFIG bin/e2e.test -v 10 -alsologtostderr -broker-image openshift/user-broker:canary
        rm -f $kubeconfig
  generated_artifacts:
    catalog-apiserver.log: '/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc login -u system:admin && /data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl logs -n kube-service-catalog -lapp=apiserver -c apiserver'
    catalog-controller.log: '/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc login -u system:admin && /data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/kubectl logs -n kube-service-catalog -lapp=controller-manager'
  system_journals:
    - origin-master.service
    - origin-master-api.service
    - origin-master-controllers.service
    - origin-node.service
    - openvswitch.service
    - ovs-vswitchd.service
    - ovsdb-server.service
    - etcd.service
