---
parent: 'common/test_cases/origin_built_release.yml'
extensions:
  actions:
    - type: "script"
      title: "build the web console container image"
      repository: "origin-web-console-server"
      timeout: 1200
      script: |-
        sudo yum --disablerepo=\* --enablerepo=origin-local-release,oso-rhui-rhel-server-releases install -y origin-clients
        make build-images
    - type: "script"
      title: "validate console starts"
      repository: "origin-web-console-server"
      timeout: 600
      # TODO For now, run cluster up to verify the console starts, but
      # eventually we will want to do more interesting e2e tests.
      script: |-
        oc cluster up --tag=latest --public-hostname=localhost --loglevel=5
  system_journals:
    - systemd-journald.service
