---
parent: 'test_cases/test_pull_request_openshift_ansible_logging.yml'
overrides:
  sync:
    - "openshift,origin=release-3.7"
    - "openshift,aos-cd-jobs=master"
    - "openshift,origin-aggregated-logging=release-3.7"
