---
parent: 'common/test_cases/origin_minimal.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "run build-cross"
      repository: "origin"
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/releases hack/env make build-cross
    - type: "host_script"
      title: "move release zips to GCS repo"
      script: |-
        location="origin-ci-test/logs/${JOB_NAME}/${BUILD_NUMBER}/artifacts/zips"
        location_url="https://storage.googleapis.com/${location}"

        mkdir -p artifacts/zips
        rsync --archive --omit-dir-times --rsh "ssh -F ./.config/origin-ci-tool/inventory/.ssh_config" --rsync-path='sudo rsync' openshiftdevel:/data/src/github.com/openshift/origin/_output/local/releases/ ./artifacts/zips || true
        gsutil -m cp -r artifacts/zips "gs://${location}"

        ref="${ORIGIN_TARGET_BRANCH-}"
        if [[ -z "${ref}" && -n "${JOB_SPEC-}" ]]; then
          ref="$( echo "${JOB_SPEC}" | jq  -r '.refs.base_ref' )"
        fi
        echo "${location_url}" > .latest-zips
        gsutil cp .latest-zips "gs://origin-ci-test/releases/openshift/origin/${ref}/.latest-zips"
