---
parent: 'test_cases/test_branch_origin_extended_conformance_install_37.yml'
overrides:
  sync:
    - "openshift,openshift-ansible=release-3.7"
    - "openshift,aos-cd-jobs=master"
    - "openshift,release=master"
