apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2020-10-21T07:43:27Z'
  generation: 5
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
      manager: Mozilla
      operation: Update
      time: '2020-10-21T13:48:54Z'
  name: jenkins-plugins
  namespace: art-jenkins
  resourceVersion: '69266116'
  selfLink: /apis/tekton.dev/v1beta1/namespaces/art-jenkins/pipelines/jenkins-plugins
  uid: 4242aba0-7556-4231-9610-7ea855e899ee
spec:
  params:
    - default: >-
        https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_jenkins/1153/pull-ci-openshift-jenkins-release-4.4-images/1306572105390755840/artifacts/build-logs/jenkins.log
      description: upstream url of jenkins log
      name: build-url
      type: string
    - default: 2.235.5
      description: target jenkins version
      name: jenkins-version
      type: string
    - default: rhaos-4.4-rhel-7
      description: target ocp branch
      name: ocp-branch
      type: string
  tasks:
    - name: collect-jenkins-plugin
      params:
        - name: build-url
          value: $(params.build-url)
        - name: jenkins-version
          value: $(params.jenkins-version)
        - name: ocp-branch
          value: $(params.ocp-branch)
      taskRef:
        kind: Task
        name: jenkins-plugin
    - name: send-email
      params:
        - name: result
          value: $(tasks.collect-jenkins-plugin.results.jobresult)
        - name: branch
          value: $(params.ocp-branch)
        - name: version
          value: $(params.jenkins-version)
        - name: plugin-list
          value: $(params.build-url)
      runAfter:
        - collect-jenkins-plugin
      taskRef:
        kind: Task
        name: jenkins-plugin-postmail
