apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2020-10-20T06:26:56Z'
  generation: 15
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
      manager: Mozilla
      operation: Update
      time: '2020-10-20T09:19:00Z'
  name: send-email
  namespace: art-jenkins
  resourceVersion: '66516717'
  selfLink: /apis/tekton.dev/v1beta1/namespaces/art-jenkins/tasks/send-email
  uid: 8072af6e-308a-412e-9d13-885c8b27043c
spec:
  params:
    - name: result
      type: string
    - name: branch
      type: string
    - name: version
      type: string
  steps:
    - image: docker.io/library/centos
      name: ''
      resources: {}
      script: >
        #!/usr/bin/env bash

        set -xeuo pipefail

        echo $(inputs.params.result)

        echo $(inputs.params.branch)

        yum -q -y install mailx postfix

        echo 'set from=ART-Tekton-jenkins.redhat.com' >> /etc/mail.rc

        echo 'set smtp="smtp.corp.redhat.com"' >> /etc/mail.rc

        echo 'search openshift.eng.bos.redhat.com' > /etc/resolv.conf

        echo 'nameserver 10.11.5.19' >> /etc/resolv.conf

        Title_success="jenkins RPM for $(inputs.params.branch) updated in
        dist-git"

        Msg_success="The Jenkins RPM for $(inputs.params.branch) has been
        updated in dist-git:\n
        http://pkgs.devel.redhat.com/cgit/rpms/jenkins/?h=$(inputs.params.branch)
        Jenkins version:$(inputs.params.version)"

        Title_error="Error during jenkins $(inputs.params.branch) RPM update on
        dist-git"

        Msg_error="The job to update the jenkins RPM in dist-git encountered an
        error:\n
        https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/art-jenkins/tekton.dev~v1beta1~Pipeline/jenkins-bump-version/Runs"

        if [[ "$(inputs.params.result)" == *success* ]]; then
          mail -v -s "$Title_success" aos-team-art@redhat.com <<< "$Msg_success"
        else
          mail -v -s "$Title_error" aos-team-art@redhat.com <<< "$Msg_error"
        fi
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
