apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: art-publish-ci-dockerconfigjson
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: art/prod/openshift-release-dev+art_quay_dev@quay.io-dockerconfigjson-plaintext
      secretKey: config.json
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: synced-art-publish-ci-dockerconfigjson
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
