apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-doomsday-creds-readonly
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: art/aws-doomsday-bucket-readonly/config
      secretKey: config
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: art/aws-doomsday-bucket-readonly/credentials
      secretKey: credentials
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: main-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: synced-aws-doomsday-readonly
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
