properties( [
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '100', daysToKeepStr: '', numToKeepStr: '100')),
    disableConcurrentBuilds(),
    disableResume(),
] )

node() {
    checkout scm

    build(
        job: '../maintenance/maintenance%2Fcleanup-locks',
        propagate: false,
    )
}
