kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "art-jenkins-slave"
  labels:
    app: "art-jenkins"
spec:
  runPolicy: "Serial"
  strategy:
    dockerStrategy:
      forcePull: true
      dockerfilePath: openshift-pipelines/images/art-jenkins-slave.Dockerfile
  source:
      git:
        uri: "https://github.com/openshift/aos-cd-jobs.git"
        ref: "master"
  output:
    to:
      kind: "ImageStreamTag"
      name: "art-jenkins-slave:latest"
  resources:
    requests:
      memory: "768Mi"
      cpu: "300m"
    limits:
      memory: "1Gi"
      cpu: "1"
