#!/usr/bin/env groovy

def contact = "nelluri@redhat.com"
def setup_tooling = SETUP_TOOLING.toString().toUpperCase()
def run_conformance = CONFORMANCE.toString().toUpperCase()
def openshift_install = OPENSHIFT_INSTALL.toString().toUpperCase()
def nodevertical = NODEVERTICAL_SCALE_TEST.toString().toUpperCase()
def mastervertical = MASTERVERTICAL_SCALE_TEST.toString().toUpperCase()
def install_openstack = OPENSTACK_INSTALL.toString().toUpperCase()
def browbeat = BROWBEAT_INSTALL.toString().toUpperCase()
def scaleup = OPENSHIFT_SCALEUP.toString().toUpperCase()
def http = HTTP_TEST.toString().toUpperCase()
def logging = LOGGING_SCALE_TEST.toString().toUpperCase()
def pgbench_test = PGBENCH_TEST.toString().toUpperCase()
def mongodb_ycsb_test = MONGODB_YCSB_TEST.toString().toUpperCase()
def podvertical = PODVERTICAL.toString().toUpperCase()
def deployments_per_ns = DEPLOYMENTS_PER_NS.toString().toUpperCase()
def ns_per_cluster = NS_PER_CLUSTER.toString().toUpperCase()
def create_jobs = CREATE_JOBS_FROM_JJB.toString().toUpperCase()
def networking = NETWORKING.toString().toUpperCase() 
def byo = BYO_SCALE_TEST.toString().toUpperCase()
def node_label = NODE_LABEL.toString()

node (node_label) {
	// setup the repo containing the pipeline scripts
	stage('cloning pipeline repo') {
		checkout scm
	}
	
	// create jenkins jobs using the jjb templated in openshift-qe jenkins 
	if (create_jobs == "TRUE") {
		load "alderaan/pipeline-scripts/create_jobs.groovy"
	}

	// stage to install openstack
	if (install_openstack == "TRUE") {
		load "alderaan/pipeline-scripts/openstack.groovy"
	}

	// stage to set up browbeat
	if (browbeat == "TRUE") {
		load "alderaan/pipeline-scripts/browbeat.groovy"
	}

	// stage to install openshift
	if (openshift_install == "TRUE") {
		load "alderaan/pipeline-scripts/openshift.groovy"
	}

	// stage to setup pbench
	if (setup_tooling == "TRUE") {
		load "alderaan/pipeline-scripts/tooling.groovy"
	}

	// stage to run conformance
	if (run_conformance == "TRUE") {
		load "alderaan/pipeline-scripts/conformance.groovy"
	}

	// stage to scaleup the cluster
	if (scaleup == "TRUE") {
		load "alderaan/pipeline-scripts/scaleup.groovy"
	}

	// stage to run nodevertical scale test
	if (nodevertical == "TRUE") {
		load "alderaan/pipeline-scripts/nodevertical.groovy"
	}

	// stage to run http scale test
	if (http == "TRUE") {
		load "alderaan/pipeline-scripts/http.groovy"
	}

	// stage to run deployments per ns test
	if ( deployments_per_ns == "TRUE" ) {
		load "alderaan/pipeline-scripts/deployments_per_ns.groovy"
	}

	// stage to run podvertical test
	if ( podvertical == "TRUE" ) {
		load "alderaan/pipeline-scripts/podvertical.groovy"
	}

	// stage to run networking test
	if ( networking == "TRUE" ) {
		load "alderaan/pipeline-scripts/networking.groovy"
	}

	// stage to run pgbench scale test
	if ( pgbench_test == "TRUE" ) {
		load "alderaan/pipeline-scripts/pgbench.groovy"
	}

	// stage to run mongodb ycsb scale test
	if ( mongodb_ycsb_test == "TRUE" ) {
		load "alderaan/pipeline-scripts/mongodbycsb.groovy"
	}

	// stage to run mastervertical scale test
	if (mastervertical == "TRUE") {
		load "alderaan/pipeline-scripts/mastervertical.groovy"
	}

	// stage to run ns_per_cluster test
	if ( ns_per_cluster == "TRUE" ) {
		load "alderaan/pipeline-scripts/ns_per_cluster.groovy"
	}

	// stage to run logging scale test
	if (logging == "TRUE") {
		load "alderaan/pipeline-scripts/logging.groovy"
	}

	// stage to run BYO scale test
	if (byo == "TRUE") {
		load "alderaan/pipeline-scripts/byo.groovy"
	}
	
	// cleanup the workspace
	stage('cleaning workspace') {
        	deleteDir()
	}

	mail(
		to: contact,
		subject: "${env.JOB_NAME} ${env.BUILD_NUMBER} completed successfully",
		body: """\
			Jenkins job: ${env.BUILD_URL}\n\n
			See the console output for more details:  ${env.BUILD_URL}consoleFull\n\n
		"""
	)
}
