kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "aos-cd-jobs-poll-master"
spec:
  runPolicy: "Serial"
  completionDeadlineSeconds: 300
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        library identifier: 'art-ci-toolkit@master', changelog: false,
          retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/openshift/art-ci-toolkit.git'])
        pollGitRefs(
          "https://github.com/openshift/aos-cd-jobs.git",
          "master",
          "update-jobs",
          "H/10 * * * *",
        )
