kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "doozer-poll-tags"
spec:
  runPolicy: "Serial"
  completionDeadlineSeconds: 300
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        library identifier: 'art-ci-toolkit@demo-openshift-pipeline', changelog: false,
          retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/vfreex/aos-cd-jobs.git'])
        pollGitRefs(
          "https://github.com/openshift/doozer.git",
          "refs/tags/v*",
          "doozer-release",
          "H/10 * * * *",
        )
