kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "doozer-release"
spec:
  runPolicy: "Parallel"
  completionDeadlineSeconds: 600
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      env:
        - name: GIT_BRANCH
          value: "master"
      jenkinsfile: |-
        library identifier: 'art-ci-toolkit@master', changelog: false,
          retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/openshift/art-ci-toolkit.git'])
        artToolRelease("https://github.com/openshift/doozer.git", params.GIT_BRANCH, "art-pypi")
