kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "elliott-poll-tags"
spec:
  runPolicy: "Serial"
  completionDeadlineSeconds: 300
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        library identifier: 'art-ci-toolkit@master', changelog: false,
          retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/openshift/art-ci-toolkit.git'])
        pollGitRefs(
          "https://github.com/openshift/elliott.git",
          "refs/tags/v*",
          "elliott-release",
          "H/10 * * * *",
        )
