kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "update-jobs"
spec:
  runPolicy: "Parallel"
  completionDeadlineSeconds: 600
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      env:
        - name: GIT_BRANCH
          value: "master"
      jenkinsfile: |-
        library identifier: 'art-ci-toolkit@master', changelog: true,
          retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/openshift/art-ci-toolkit.git'])
        artUpdateJobs("https://github.com/openshift/aos-cd-jobs.git", params.GIT_BRANCH)
