properties([
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '100')),
    disableConcurrentBuilds(),
    disableResume(),
])

failed = false

node() {
    timestamps {
    checkout scm
    buildlib = load("pipeline-scripts/buildlib.groovy")
    commonlib = buildlib.commonlib

    commonlib.shell('sudo systemctl restart stunnel')

    try {
        timeout(activity: true, time: 60, unit: 'MINUTES') {
            b = build(
                job: '../scanning/scanning%2Fokd-images-health',
                parameters: [
                    string(name: 'VERSIONS', value: commonlib.okdVersions.join(',')),
                ],
                propagate: false,
            )
            failed |= (b.result != "SUCCESS")
        }
    } catch(te) {
        failed = true
    }

    buildlib.cleanWorkspace()
    }
}

currentBuild.result = failed ? "FAILURE" : "SUCCESS"
