---
parent: 'common/test_cases/origin_release.yml'
overrides:
  timer: 'H H * * *'
  email:
    - skuznets@redhat.com
    - deads2k@redhat.com
    - jliggitt@redhat.com
    - mkhan@redhat.com
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        JUNIT_REPORT='true' make test-extended SUITE=ldap_groups