---
parent: 'common/test_cases/origin_release.yml'
extensions:
  parameters:
    - name: "SUITE"
      description: "Which shell file in the <a href='https://github.com/openshift/origin/tree/master/test/extended'><code>origin/test/extended/</code></a> directory to run."
    - name: "FOCUS"
      description: "Literal string to pass to <code>--ginkgo.focus</code>"
  actions:
    - type: "forward_parameters"
      parameters:
        - SUITE
        - FOCUS
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        # rosie-bot does not know how to split suite and focus
        # so we need to detect that she is doing her best and
        # help her out by parsing the input she gives
        if [[ -z "${FOCUS:-}" && "${SUITE}" =~ ^(.*)\((.*)\)$ ]]; then
            SUITE="${BASH_REMATCH[1]}"
            FOCUS="${BASH_REMATCH[2]}"
        fi
        JUNIT_REPORT='true' make test-extended SUITE="${SUITE}" FOCUS="${FOCUS:-}"