kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: "art-tools-tester"
  labels:
    app: "artcd"
spec:
  runPolicy: "Serial"
  strategy:
    dockerStrategy:
      forcePull: true
      dockerfilePath: tekton-pipelines/images/art-tools-tester/Containerfile
  source:
    git:
      uri: "https://github.com/openshift/aos-cd-jobs.git"
      ref: "master"
  output:
    to:
      kind: "ImageStreamTag"
      name: "art-tools-tester:latest"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  triggers:
  - type: ConfigChange
