kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "artcd-image"
  labels:
    app: "artcd"
spec:
  runPolicy: "Serial"
  strategy:
    dockerStrategy:
      forcePull: true
      dockerfilePath: tekton-pipelines/images/artcd/Dockerfile
  source:
      git:
        uri: "https://github.com/openshift/aos-cd-jobs.git"
        ref: "master"
  output:
    to:
      kind: "ImageStreamTag"
      name: "artcd:latest"
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"
  triggers:
  - type: ConfigChange
