kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: poll-for-prs-state
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
