apiVersion: v1
kind: ImageStream
metadata:
  name: "smee-client"
  labels:
    app: "artcd"
spec:
  dockerImageRepository: "quay.io/openshift-art/smee-client"
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/openshift-art/smee-client:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
