#!/usr/bin/env groovy

node() {
    checkout scm
    commonlib = load("pipeline-scripts/commonlib.groovy")

    commonlib.describeJob("rhcos", """
This job is meant to be triggered by remote API calls (namely from ocp4_scan). It will forward the call to 
<a href="https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Frhcos">rhcos</a>,
that being part of a multibranch pipeline could not be configured to receive remote triggers directly.<br>
In this context, the only <strong>BUILD_VERSION</strong> and <strong>NEW_BUILD</strong> params are required.
    """)

    // Expose properties for a parameterized build
    properties(
        [
            disableResume(),
            buildDiscarder(
                logRotator(
                    artifactDaysToKeepStr: '365',
                    daysToKeepStr: '365')),
            [
                $class: 'ParametersDefinitionProperty',
                parameterDefinitions: [
                    commonlib.mockParam(),
                    commonlib.ocpVersionParam('BUILD_VERSION', '4'),
                    booleanParam(
                        name: "NEW_BUILD",
                        description: "(Multi pipeline only) Request a new build from the RHCOS pipeline even when it finds no changes from the last.",
                        defaultValue: false
                    ),
                    string(name: "TRIGGERED_FROM", trim: true),
                ]
            ],
        ]
    )

    commonlib.checkMock()
    currentBuild.displayName = "#${currentBuild.number} - ${params.BUILD_VERSION}"

    echo "Triggered from ${TRIGGERED_FROM}"

    build(
        job: '../aos-cd-builds/build%252Frhcos/',
        propagate: false,
        parameters: [
            string(name: 'BUILD_VERSION', value: params.BUILD_VERSION),
            booleanParam(name: 'NEW_BUILD', value: params.NEW_BUILD)
        ]
    )
}
